language: erlang
otp_release:
 - R16B
 - R15B03
 - R14B04
before_install:
 - sudo apt-key add ./test/ubuntu_extras_pub_key
 - sudo add-apt-repository -y ppa:cassou/emacs
 - sudo apt-get update -qq
 - sudo apt-get install -y -qq ${EMACS} erlang-mode erlang-debugger
 - ./test/install-ert.sh
env:
 - EMACS=emacs23
 - EMACS=emacs24
script:
 - "make -s test"
